require("nvim-options")
require("config.lazy")
vim.cmd("colorscheme rasmus")
require("config.mason")
require("config.mason-lspconfig")
require("config.rust-tools")
require("nvim-diagnostics")
require("config.cmp")
require("config.conform")
require("config.mason-conform")
require("config.telescope")
require("telescope-options")
require("config.which-key")
